### ISSUE TITLE
M1 Mac support

### ISSUE THREAD

**Issue by srid** [srid/haskell-template#1]
Make `nix build` (and `bin/run`) succeed on M1 Mac with native Nix installed.

No rosetta.

- [x] `nix build` works
- [x] `nix develop` works, with HLS, ormolu, etc.
- [ ] GitHub CI (pending on https://github.com/actions/virtual-environments/issues/2187 )

**Comment by srid** [comment]
`/nix/store/7vjmcgcxm0jy0w2jsyk99n0kiq52q296-compiler-rt-libc-9.0.1.drv` failed to build:

```
[ 48%] Building C object lib/builtins/CMakeFiles/clang_rt.cc_kext_arm64_osx.dir/floatsidf.c.o
/tmp/nix-build-compiler-rt-libc-9.0.1.drv-0/compiler-rt-9.0.1.src/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:168:31: error: invalid application of 'sizeof' to an incomplete
  unsigned struct_stat64_sz = sizeof(struct stat64);
                              ^     ~~~~~~~~~~~~~~~
/tmp/nix-build-compiler-rt-libc-9.0.1.drv-0/compiler-rt-9.0.1.src/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:168:45: note: forward declaration of '__sanitizer::stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                                            ^
/tmp/nix-build-compiler-rt-libc-9.0.1.drv-0/compiler-rt-9.0.1.src/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:194:33: error: invalid application of 'sizeof' to an incomplete
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                ^     ~~~~~~~~~~~~~~~~~
/tmp/nix-build-compiler-rt-libc-9.0.1.drv-0/compiler-rt-9.0.1.src/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:194:47: note: forward declaration of '__sanitizer::statfs64'
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                              ^
[ 49%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_arm64_osx.dir/fixunsdfdi.c.o
2 errors generated.
make[2]: *** [lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/build.make:370: lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/sanitizer_platform_limits_
make[1]: *** [CMakeFiles/Makefile2:851: lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/all] Error 2
```

**Comment by srid** [comment]
I should note this happens in nix-shell and not nix-build: https://github.com/NixOS/nixpkgs/issues/147739

**Comment by srid** [comment]
After advancing Nixpkgs,

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/3998/143918491-62802845-5a00-4bf6-a249-77b31f32a93b.png">

**Comment by srid** [comment]
@sternenseemann - Any chance I can entertain your interest in this? 

I advanced Nixpkgs past your https://github.com/NixOS/nixpkgs/pull/147260 hoping that that might fix it (maybe it fix the llvm error above), but still I can't build even cabal2nix (fails at `th-abstraction`). As an aside, I wonder why cabal2nix's dependencies are not cached.

**Comment by sternenseemann** [comment]
> Any chance I can entertain your interest in this?

I entertain the littlest interest in `aarch64-darwin` possible to be honest, I don't have no M1 machine nor plan purchasing one, so the whole platform just causes me a lot of annoyance I can't do anything about…

> maybe it fix the llvm error above

Indeed, LLVM 9 was used for `haskellPackages` before which did not support `aarch64-darwin` at all. LLVM >= 11 should support it though, hence the build failure disappears.

> but still I can't build even cabal2nix (fails at th-abstraction).

Looking at the error it seems to me that this might be some kind of code signing issue, you should be able to confirm this using the `log(1)` utility. My first instinct was that this was due to execution of the test suite, but this doesn't seem to be the case as `./Setup` actually gets killed, at seemingly random places in other builds. Interestingly this seemingly only started happening *after* upgrading LLVM, e. g. `th-abstraction` [was building with LLVM 9](https://hydra.nixos.org/build/159290874).

At this point, I can't really guess what the issue might be. Worth a try might be recompiling GHC and the package set using LLVM 11.

Regrettably, the contributed support for `aarch64-darwin` has been limited to getting GHC to compile and very little work has gone into actually making the packages produced by it work properly.

> As an aside, I wonder why cabal2nix's dependencies are not cached.

Well, it is kind of hard to cache dependencies that [don't build](https://hydra.nixos.org/build/159813528).

**Comment by sternenseemann** [comment]
Should be fixed on current nixpkgs master.

**Comment by srid** [comment]
Awesome, @sternenseemann ! 🕺🏿 

It mostly works now after a0672b6bc68d1e9c9350837652c26b87852064c8. One final thing left to resolve is build failures for `ghcid`, `ormolu`, etc (see below) ... but `nix build` with these build tools commented out works.

```
error: cycle detected in build of '/nix/store/am90h7yjq0jdk5ha80r2gwq5xs1kqfnl-ghcid-0.8.7.drv' 
  in the references of output 'bin' from output 'out'
```

Looks to be this issue: https://github.com/NixOS/nixpkgs/issues/140774

**Comment by sternenseemann** [comment]
> Looks to be this issue: NixOS/nixpkgs#140774

Yes.
